version: '3.8'

services:
  web:
    image: php:8.2-apache
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    command: >
      sh -c "docker-php-ext-install mysqli && apache2-foreground"

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: baza
      MYSQL_USER: admin
      MYSQL_PASSWORD: supersecret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  # Persist database data

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: admin
      PMA_PASSWORD: supersecret
    depends_on:
      - db

networks:
  default:
    driver: bridge

volumes:
  db_data:  # Define the volume for database persistence