version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: baza
      MYSQL_USER: admin
      MYSQL_PASSWORD: supersecret
    ports:
      - "3306:3306"
